title: Sartu Hussein # your name (or website title) here
logo: "/images/my_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Sartu Hussein and I'm currently going for my Bachelor's in Comp Sci. I'm looking for hands on oppurtunities where I can apply my tech skills in the field.
  <br><br>
  <a href="www.linkedin.com/in/sartu-hussein">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-89YR903VR0 # your Google Analytics tracking ID here
